### Recipes Index
Get http://localhost:3000/recipes

### Recipes Create
POST http://localhost:3000/recipes/
Content-Type: application/json

{
"name": "test",
"chef": "test chef"
}

### Recipes Show
GET http://localhost:3000/recipes/

### Recipes Update
PATCH http://localhost:3000/recipes/

### Recipes Destroy
DELETE http://localhost:3000/recipes/



### Ingredients Index
GET http://localhost:3000/ingredients

### Ingredients Create
POST http://localhost:3000/ingredients/
Content-Type: application/json

{
"name": "test",
"measurement": "shit, shingles"
}

### Ingredients Show
GET http://localhost:3000/ingredients/

### Ingredients Destroy
DELETE http://localhost:3000/ingredients/

###Users Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###Sessions Create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}